#### Understanding the features of tensorflow and implementing the graph with tensorboard

In [1]:
#Importing the tensorflow library
import tensorflow as tf

In [2]:
#Running in default mode - differed execution
#We will not get the internal details and no graph functionalities availaible
tf.compat.v1.disable_eager_execution()
a=tf.constant(2.0)
print(a)

Tensor("Const:0", shape=(), dtype=float32)


In [3]:
#Creating a session
session = tf.compat.v1.Session()

In [4]:
print(session.run(a))

2.0


In [5]:
print("Type of a : %s" % type(a))

Type of a : <class 'tensorflow.python.framework.ops.Tensor'>


In [6]:
#Addition
b=tf.constant(3.0)
c=a+b
print([b,c])

[<tf.Tensor 'Const_1:0' shape=() dtype=float32>, <tf.Tensor 'add:0' shape=() dtype=float32>]


In [7]:
print(session.run(c))

5.0


In [8]:
#Multiplication
x1=tf.constant([1,2,3,4])
x2=tf.constant([5,6,7,8])
print([x1,x2])

[<tf.Tensor 'Const_2:0' shape=(4,) dtype=int32>, <tf.Tensor 'Const_3:0' shape=(4,) dtype=int32>]


In [9]:
print(session.run(x1))

[1 2 3 4]


In [10]:
res=tf.multiply(x1,x2)
print(session.run(res))

[ 5 12 21 32]


In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x=tf.constant(35,name='x')
print(x)
y = tf.Variable(x+5,name='y')
print("Type of x : %s" % type(x))
print("Type of y : %s" % type(y))

Instructions for updating:
non-resource variables are not supported in the long term
Tensor("x:0", shape=(), dtype=int32)
Type of x : <class 'tensorflow.python.framework.ops.Tensor'>
Type of y : <class 'tensorflow.python.ops.variables.RefVariable'>


In [12]:
model = tf.compat.v1.global_variables_initializer()
with tf.Session() as session:
    session.run(model)
    print(session.run(y))

40


In [13]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
adder_node=a+b
#Initialize the session
session=tf.Session()
#Print the result
print(session.run(adder_node,{a:[1,3],b:[2,4]}))
session.close()

[3. 7.]


In [14]:
x=tf.placeholder("float",[None,3])
y=x*2
with tf.Session() as session:
  x_data=[[1,2,3],[4,5,6]]
  result=session.run(y,feed_dict={x : x_data})
  print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [15]:
print(x)

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [17]:
x = tf.constant(14, name='x')
print(x)

y = tf.Variable(x+5, name='y')

print("Type of a : %s" % type(x))
print("Type of a : %s" % type(y))

Tensor("x_1:0", shape=(), dtype=int32)
Type of a : <class 'tensorflow.python.framework.ops.Tensor'>
Type of a : <class 'tensorflow.python.ops.variables.RefVariable'>


In [18]:
init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    # Usage passing the session explicitly.
    print(y.eval(sess))
    # Usage with the default session.  The 'with' block
    # above makes 'sess' the default session.
    print(y.eval())

19
19
